[platformio]
default_envs = esp32dev
core_dir = .platformio-local
platforms_dir = .platformio-local/platforms
packages_dir = .platformio-local/packages
cache_dir = .platformio-local/.cache
build_dir = .platformio-local/build
libdeps_dir = .platformio-local/libdeps

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
